// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalizedLearningPath.Data;

#nullable disable

namespace PersonalizedLearningPath.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220063208_AddLearningPathEngine")]
    partial class AddLearningPathEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.Property<int>("ConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConceptId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ConceptId");

                    b.HasIndex("SkillId", "Name")
                        .IsUnique();

                    b.ToTable("Concepts", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.ConceptPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("SkillId", "ConceptId", "PrerequisiteId")
                        .IsUnique();

                    b.ToTable("ConceptPrerequisites", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("TotalVideos")
                        .HasColumnType("int");

                    b.Property<string>("YoutubeVideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("CourseId");

                    b.HasIndex("SkillId", "CourseLevel", "SequenceOrder");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.LearningPath", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PathId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PathId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "Status");

                    b.ToTable("LearningPaths", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.LearningPathCourse", b =>
                {
                    b.Property<int>("PathCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PathCourseId"));

                    b.Property<int>("CompletionPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PathId")
                        .HasColumnType("int");

                    b.HasKey("PathCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("PathId", "CourseId")
                        .IsUnique();

                    b.ToTable("LearningPathCourses", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("ChoiceA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChoiceB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChoiceC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("TreeIndex")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("SkillId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalAnswered")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkillAssessments", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "CompletedAt");

                    b.ToTable("UserSkillsHistory", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserVideoProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoIndex")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId", "VideoIndex")
                        .IsUnique();

                    b.ToTable("UserVideoProgress", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.ConceptPrerequisite", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Concept", "Concept")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.Concept", "Prerequisite")
                        .WithMany("Dependents")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Course", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("Courses")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.LearningPath", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("LearningPaths")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.User", "User")
                        .WithMany("LearningPaths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.LearningPathCourse", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Course", "Course")
                        .WithMany("LearningPathCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.LearningPath", "LearningPath")
                        .WithMany("LearningPathCourses")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LearningPath");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Question", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("Questions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillAssessment", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("UserSkillAssessments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.User", "User")
                        .WithMany("UserSkillAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillHistory", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.User", "User")
                        .WithMany("UserSkillHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserVideoProgress", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Course", "Course")
                        .WithMany("UserVideoProgress")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.User", "User")
                        .WithMany("UserVideoProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Course", b =>
                {
                    b.Navigation("LearningPathCourses");

                    b.Navigation("UserVideoProgress");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.LearningPath", b =>
                {
                    b.Navigation("LearningPathCourses");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Skill", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("LearningPaths");

                    b.Navigation("Questions");

                    b.Navigation("UserSkillAssessments");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.User", b =>
                {
                    b.Navigation("LearningPaths");

                    b.Navigation("UserSkillAssessments");

                    b.Navigation("UserSkillHistory");

                    b.Navigation("UserVideoProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
