// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalizedLearningPath.Data;

#nullable disable

namespace PersonalizedLearningPath.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220021135_AddConceptDependencyGraph")]
    partial class AddConceptDependencyGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.Property<int>("ConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConceptId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ConceptId");

                    b.HasIndex("SkillId", "Name")
                        .IsUnique();

                    b.ToTable("Concepts", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.ConceptPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("SkillId", "ConceptId", "PrerequisiteId")
                        .IsUnique();

                    b.ToTable("ConceptPrerequisites", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("ChoiceA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChoiceB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChoiceC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("TreeIndex")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("SkillId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalAnswered")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkillAssessments", (string)null);
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.ConceptPrerequisite", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Concept", "Concept")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.Concept", "Prerequisite")
                        .WithMany("Dependents")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Question", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("Questions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.UserSkillAssessment", b =>
                {
                    b.HasOne("PersonalizedLearningPath.Models.Skill", "Skill")
                        .WithMany("UserSkillAssessments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalizedLearningPath.Models.User", "User")
                        .WithMany("UserSkillAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Concept", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.Skill", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("UserSkillAssessments");
                });

            modelBuilder.Entity("PersonalizedLearningPath.Models.User", b =>
                {
                    b.Navigation("UserSkillAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
